name: Publish Unit Test Results

on:
  workflow_run:
    workflows: ["Build Tests"]
    types:
      - completed

jobs:
    check:
       uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/publishTestResults.yml@master




